### PR TITLE
Add profile page and return page

### PR DESCRIPTION
**Pull request by GraceFu**
- add profile page (enabled by clicking profile icon in menu)
- add return button and page
- fix a few typos (manu->menu, desitination->destination, recieve->receive)

### CODE REVIEW

**Review by Kay7777 — CHANGES_REQUESTED** [review]
Files need to be reviewed:
app/src/main/res/layout/activity_main.xml
app/src/main/java/com/example/booktruck/MainActivity.java
app/src/main/AndroidManifest.xml

**Review by GraceFu — COMMENTED** [review]
merge branch with master

**Review by Kay7777 — CHANGES_REQUESTED** [review]
app/src/main/AndroidManifest.xml 40/41 lines are not updated to date.

**Review by Kay7777 — APPROVED** [review]
LGTM

**Pull request merged**
